

default: main.cpp
	g++ main.cpp -o main.exe -lm -fopenmp -std=c++17

# must use g++ NOT gcc  when using chono, because g++ knows where the c standard libraries are and links them, this could be done manually with gcc